/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    ElCalendar: typeof import('element-plus/es')['ElCalendar']
    ElContainer: typeof import('element-plus/es')['ElContainer']
    ElHeader: typeof import('element-plus/es')['ElHeader']
    ElMain: typeof import('element-plus/es')['ElMain']
    ElMenu: typeof import('element-plus/es')['ElMenu']
    ElMenuItem: typeof import('element-plus/es')['ElMenuItem']
    ElSubMenu: typeof import('element-plus/es')['ElSubMenu']
    ElTabPane: typeof import('element-plus/es')['ElTabPane']
    ElTabs: typeof import('element-plus/es')['ElTabs']
    ElText: typeof import('element-plus/es')['ElText']
    Frame: typeof import('./src/components/frame.vue')['default']
    Goto: typeof import('./src/components/goto.vue')['default']
    Header: typeof import('./src/components/header.vue')['default']
    HomeNavigate: typeof import('./src/components/Home-navigate.vue')['default']
    Music: typeof import('./src/components/music.vue')['default']
    Navigate: typeof import('./src/components/navigate.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Tex: typeof import('./src/components/Tex.vue')['default']
    Todo: typeof import('./src/components/todo.vue')['default']
    TodoInput: typeof import('./src/components/todo/TodoInput.vue')['default']
    TodoItem: typeof import('./src/components/todo/TodoItem.vue')['default']
    TodoList: typeof import('./src/components/todo/TodoList.vue')['default']
    Weather: typeof import('./src/components/weather.vue')['default']
  }
}
